<%--
  Created by IntelliJ IDEA.
  User: J.R. Price
  Date: 10/19/2019
  Time: 6:06 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Whos playing</title>
</head>
<body>
<center>
    <h2>How it works:</h2>
    <p>Trendy Words Game is a word game that awards point based on how "trendy" it is by taking information form Google Trends. First a word is randomly generated by the computer and then the teams chose a words to go with it. lets say the computer generates the word "House" and then player 1 finishes it with "party" but player 2 says "painter". Now players are awarded points based on how many searches its had recently. Each game has multiple rounds and the player with the most points at the end wins. Players with the same word will be awarded the sames points but whoever typed it first gets an extra 5 points</p>
</center>
</body>
</html>
